### ISSUE TITLE
Change the frontend

### ISSUE THREAD

**Issue by JeanDidier** [insilichem/insilichem.github.io#1]
I believe that the first page that pops should state something like:

insilichem.bio - Molecular Modeling for study and design of chemobiological (or Chemobiotechnological) systems

The concept of solutions is something more towards engineering and consulting, we are (for at least a few more months) pure academy.

**Comment by jaimergp** [comment]
Like this? 

![screenshot from 2016-01-15 15-43-13](https://cloud.githubusercontent.com/assets/2559438/12355691/bb5e36aa-bb9e-11e5-9ff1-c29729116a7a.png)

**Comment by JeanDidier** [comment]
yep
