### ISSUE TITLE
Team members

### ISSUE THREAD

**Issue by JeanDidier** [insilichem/insilichem.github.io#4]
Hi,

would be great to add an entry with a list of members of the group with a short description and the possibility for them to link to a home webpage or eventually the possibility to set up his/her directly on the website.

JD

**Comment by jaimergp** [comment]
Sure! We should start compiling the list of members (this is a good place).

A collection of links to some webs/linkedin/any social network (like the bottom of the page) they want should be enough. I don't think we must invest the time and resources in providing personal webpage they won't probably update anyway.

**Comment by JeanDidier** [comment]
OK, this is the list:

Me, you, Lur, Dani, Jordi as a starter. 

There should be a short intro/CV for each of us. Then the link to other places. People that visit the web would not necessary fly other individual webpages but would appreciate a glance. Key information should include: background, year of incorporation, professional state (Ph.d, undergraduate etc.) and field of research. A bullet point section would be ok.
the links? linkedin, google scholar, research gate and personal web page should be enough I would say

**Comment by jaimergp** [comment]
I've started to tackle this. Please, provide:
- Desired profile picture (250x250 minimum resolution, 500x500 ideally)
- Links to relevant sites (LinkedIn, G Scholar, ResearchGate, Personal Webpage)
- Position (2 words max)
- Background (2 words max)
- Field of research (16 words max)

**Comment by JeanDidier** [comment]
I don't see recipients. Should I give you the info myself or are the others
receiving your mail?

El dj., 28 gen. 2016 , 16:49 Jaime RGP notifications@github.com va
escriure:
